In [11]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import sklearn
from sklearn.datasets import load_boston
boston = load_boston()

In [12]:
df_x = pd.DataFrame(boston.data, columns = boston.feature_names)
df_y = pd.DataFrame(boston.target)

In [13]:
df_x.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000

In [14]:
reg = LinearRegression()

In [15]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.33, random_state=42)

In [16]:
reg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [17]:
reg.coef_

array([[-1.28749718e-01,  3.78232228e-02,  5.82109233e-02,
         3.23866812e+00, -1.61698120e+01,  3.90205116e+00,
        -1.28507825e-02, -1.42222430e+00,  2.34853915e-01,
        -8.21331947e-03, -9.28722459e-01,  1.17695921e-02,
        -5.47566338e-01]])

In [18]:
y_pred = reg.predict(x_test)
print(y_pred)

[[28.53469469]
 [36.6187006 ]
 [15.63751079]
 [25.5014496 ]
 [18.7096734 ]
 [23.16471591]
 [17.31011035]
 [14.07736367]
 [23.01064388]
 [20.54223482]
 [24.91632351]
 [18.41098052]
 [-6.52079687]
 [21.83372604]
 [19.14903064]
 [26.0587322 ]
 [20.30232625]
 [ 5.74943567]
 [40.33137811]
 [17.45791446]
 [27.47486665]
 [30.2170757 ]
 [10.80555625]
 [23.87721728]
 [17.99492211]
 [16.02608791]
 [23.268288  ]
 [14.36825207]
 [22.38116971]
 [19.3092068 ]
 [22.17284576]
 [25.05925441]
 [25.13780726]
 [18.46730198]
 [16.60405712]
 [17.46564046]
 [30.71367733]
 [20.05106788]
 [23.9897768 ]
 [24.94322408]
 [13.97945355]
 [31.64706967]
 [42.48057206]
 [17.70042814]
 [26.92507869]
 [17.15897719]
 [13.68918087]
 [26.14924245]
 [20.2782306 ]
 [29.99003492]
 [21.21260347]
 [34.03649185]
 [15.41837553]
 [25.95781061]
 [39.13897274]
 [22.96118424]
 [18.80310558]
 [33.07865362]
 [24.74384155]
 [12.83640958]
 [22.41963398]
 [30.64804979]
 [31.59567111]
 [16.34088197]
 [20.9504304 ]
 [16.70145875]
 [20.23215646]
 [26.1437865 ]
 [31.12160889]
 [11.89762768]
 [20.45432404]
 [27.48356359]
 [10.89034224]
 [16.77707214]
 [24.02593714]
 [ 5.44691807]
 [21.35152331]
 [41.27267175]
 [18.13447647]
 [ 9.8012101 ]
 [21.24024342]
 [13.02644969]
 [21.80198374]
 [ 9.48201752]
 [22.99183857]
 [31.90465631]
 [18.95594718]
 [25.48515032]
 [29.49687019]
 [20.07282539]
 [25.5616062 ]
 [ 5.59584382]
 [20.18410904]
 [15.08773299]
 [14.34562117]
 [20.85155407]
 [24.80149389]
 [-0.19785401]
 [13.57649004]
 [15.64401679]
 [22.03765773]
 [24.70314482]
 [10.86409112]
 [19.60231067]
 [23.73429161]
 [12.08082177]
 [18.40997903]
 [25.4366158 ]
 [20.76506636]
 [24.68588237]
 [ 7.4995836 ]
 [18.93015665]
 [21.70801764]
 [27.14350579]
 [31.93765208]
 [15.19483586]
 [34.01357428]
 [12.85763091]
 [21.06646184]
 [28.58470042]
 [15.77437534]
 [24.77512495]
 [ 3.64655689]
 [23.91169589]
 [25.82292925]
 [23.03339677]
 [25.35158335]
 [33.05655447]
 [20.65930467]
 [38.18917361]
 [14.04714297]
 [25.26034469]
 [17.6138723 ]
 [20.60883766]
 [ 9.8525544 ]
 [21.06756951]
 [22.20145587]
 [32.2920276 ]
 [31.57638342]
 [15.29265938]
 [16.7100235 ]
 [29.10550932]
 [25.17762329]
 [16.88159225]
 [ 6.32621877]
 [26.70210263]
 [23.3525851 ]
 [17.24168182]
 [13.22815696]
 [39.49907507]
 [16.53528575]
 [18.14635902]
 [25.06620426]
 [23.70640231]
 [22.20167772]
 [21.22272327]
 [16.89825921]
 [23.15518273]
 [28.69699805]
 [ 6.65526482]
 [23.98399958]
 [17.21004545]
 [21.0574427 ]
 [25.01734597]
 [27.65461859]
 [20.70205823]
 [40.38214871]]

In [19]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_test, y_pred))

20.72402343733974